"""Persistent application settings via QSettings."""
from __future__ import annotations

from typing import Any

from PyQt6.QtCore import QSettings

from core.logger import get_logger
from core.platform_paths import default_argyll_bin_dir, is_macos, is_windows

log = get_logger(__name__)

DEFAULTS: dict[str, Any] = {
    # ArgyllCMS
    "argyll_bin_path":           default_argyll_bin_dir(),
    "custom_output_path":        "",       # "" = ~/ChromIQ/
    # Step 1 — chart creation
    "chart_mode":                "guided",
    "chart_instrument":          "i1",
    "chart_paper":               "A4",
    "chart_pages":               1,
    "chart_double_density":      False,
    "chart_disable_left_border": False,
    # Print info into the i1Pro left clip strip (auto-applies in guided when
    # gating holds: instrument i1/p3, -L off, paper >= A4/Letter).
    "chart_left_clip_info":      False,
    "targen_device_type":        "2",      # Print RGB
    "targen_patches":            0,        # 0 = auto-computed
    # Neutral-patch anchor: the total patch count at which a chart gets the
    # standard 32 grey / 4 white / 4 black. Neutral counts scale relative to
    # this in both Guided and Manual mode (lower = denser, higher = sparser).
    # Default 560 = the i1Pro+A4-landscape reference layout; see
    # workflow.chart_creator.REF_BUDGET. Floors/caps still apply.
    "grey_ramp_reference":       560,
    "targen_good_mode":          True,
    "targen_extra_args":         "",
    "printtarg_dpi":             300,
    "printtarg_extra_args":      "",
    # i1Pro chart layout default: combined -m/-M margin + -a patch scale preset.
    # Applied when instrument == "i1" in both guided and manual modes. Other
    # instruments (p3, CM, SS) are unaffected and keep their existing defaults.
    # See data/patch_db.I1PRO_DEFAULT_PRESETS for the available preset keys.
    "i1pro_default_preset":      "m10_a0.95",
    # Custom ChromIQ chart-layout engine (issue #93). When True, charts are
    # generated by workflow/layout_engine instead of ArgyllCMS printtarg.
    # This toggle governs the MANUAL tab (default OFF — printtarg stays the
    # Manual fallback, incl. the printtarg-based built-in presets). GUIDED mode
    # always uses the engine now: it reproduces printtarg's Guided geometry for
    # every instrument/paper/option (verified 161/161, see the parity matrix) —
    # see _should_use_engine. Affects chart *generation* only, never measurement.
    "use_chromiq_layout_engine": False,
    # Layout-engine presets (issue #93) are stored as user-browsable .json files
    # under presets_dir()/"Chart Layout" via core.preset_store — like the manual
    # tab presets — not in QSettings, so they can be shared/backed up externally.
    # When True, on i1Pro / i1Pro 3+ charts at paper >= A4/Letter:
    #   • Force printtarg -L (no native clip strip).
    #   • Post-process the TIFF to shift patches right by ~28 mm, creating a
    #     fresh white strip on the left.
    #   • Always stamp ChromIQ left-clip content (spectrum bar + 3 text columns)
    #     into that strip.
    #   • Skip the right-margin command/notes stamp (its area is now off-page).
    # Outside those conditions the setting has no effect.
    "i1pro_chromiq_clip_style":  False,
    # Auto-update the Create-Chart preview when a layout setting changes (only
    # once a chart has been generated/loaded). Re-lays-out the existing patch set
    # so it's fast (no targen), and suppresses the "room left on the last page"
    # pop-up while on. Default off (opt-in).
    "auto_update_preview":       False,
    # Step 2 — print
    "last_printer":              "",
    "print_input_slot":          "",
    "print_media":               "",
    "print_media_type":          "",
    "print_quality":             "",
    # Default to the OS print dialog on macOS *and* Windows.  The macOS native
    # path now reliably disables colour management for every driver — including
    # Canon, which previously colour-managed the chart regardless — by
    # replicating ColorByte Print-Tool's recipe: it declares the printer's own
    # device profile as the *application* output intent (identity transform =
    # true passthrough) and sets AP_ApplicationColorMatching on the session, in
    # addition to the driver's own no-colour key (e.g. Canon CNIJIntent2=1001).
    # See workflow/native_print_macos.py.  macOS users can still opt back to
    # ChromIQ's lp path in Settings; Windows has no lp path so it stays
    # force-locked on there (in get()).
    "use_native_print_dialog":   is_windows() or is_macos(),
    "confirm_before_printing":   True,
    # ChromIQ lp pipeline only (macOS): when CUPS rejects PostScript (every
    # non-PostScript printer — Apple's CUPS ships no PS→raster chain), retry
    # with a ChromIQ-generated exact-size PDF instead of the raw TIFF.  The
    # raw-TIFF route hands placement to Apple's cgimagetopdf, which shrinks
    # full-page charts ~3% to fit the imageable area and ignores every
    # ppi/scaling option; the PDF places the chart 1:1 (overhang clips at the
    # hardware margins, like ColorSync Utility) and stays colour-passthrough
    # (untagged device RGB, verified no-ink against Canon + Epson PPDs).
    # Irrelevant while use_native_print_dialog is on (no lp jobs then) —
    # Settings greys it out accordingly.  Off until hardware-verified.
    "pdf_print_fallback":        False,
    # Step 3 — measure
    "measure_disable_bidir":       True,
    # Suppresses the "forcing bidirectional on a non-randomised chart" warning
    # dialog once the user ticks "Don't show this again".
    "measure_hide_nonrandom_bidir_warning": False,
    "measure_suppress_warnings":   True,
    "measure_extra_args":          "",
    "measure_tolerance_enabled":           True,
    "measure_tolerance_value":             0.7,
    "manual2_chartread_tolerance_enabled": True,
    # TI2 layout editor — randomised tagging. Well-mixed charts are tagged
    # automatically on save; this remembers whether to FORCE the tag on a
    # layout the safety check considers structured, and whether the user has
    # dismissed the force-risk warning.
    "ti2_editor_force_tag":              False,
    "ti2_editor_force_tag_hide_warning": False,
    # Step 4 — profile
    "colprof_algorithm":         "l",
    "colprof_quality":           "m",
    "colprof_extra_args":        "",
    # Step 5 — check & refine
    "profcheck_de_formula":      "k",       # "" / "-c" / "-k"
    "profcheck_intent":          "a",       # "a" = absolute,  "r" = relative
    "profcheck_sort":            True,
    "profcheck_verbosity":       "2",       # "1" = summary,  "2" = per-patch
    "profcheck_fwa_enabled":     False,
    "profcheck_fwa_illum":       "D50",
    "profcheck_illum":           "D50",
    "profcheck_observer":        "1931_2",
    "profcheck_prune_enabled":      False,
    "profcheck_prune_value":        3.0,
    "profcheck_x3dom":              False,
    "profcheck_refine_threshold":   2.0,
    # Step 5 — gamut viewer (iccgamut)
    "gamut_intent":              "a",     # a=absolute, r=relative, p=perceptual, s=saturation
    "gamut_pcs":                 "l",     # l=Lab, j=CIECAM02 Jab
    "gamut_sres":                20.0,    # surface resolution
    "gamut_axes":                True,    # show axes + white/black point
    "gamut_cusps":               False,   # cusp markers
    "gamut_edges":               False,   # edge plot
    "gamut_function":            "f",     # f=forward, b=backward
    "gamut_themed_colors":       True,   # remap vertex colors to app palette
    # Calibration workflow
    "calibration_mode":          False,
    "printcal_smoothing":        1.0,
    "printcal_verbosity":        1,
    "printcal_mode":             "initial",
    "applycal_mode":             "apply",
    "applycal_verbose":          False,
    # ChromIQ-style refinement: merge a pre-conditioning profile's measurement
    # data into the freshly measured chart before building (see workflow/ti3_merge.py)
    "chromiq_refinement":        False,
    # "Read again & average" — master switch. OFF (default) restores the classic
    # behaviour: a finished full read proceeds straight to Build Profile. ON adds
    # the post-read completion dialog offering measure-again / average.
    "averaging_enabled":         False,
    # When averaging is enabled, how repeated reads are combined: "mean" | "median"
    # (median == argyll `average -e`; only differs from mean at 3+ reads)
    "average_method":            "mean",
    # UI state
    "window_geometry":           None,
    "active_tab":                0,
    "restore_last_tab":          True,
    "restore_last_session":      False,
    "appearance":                "auto",   # "light" | "dark" | "auto"
    "language":                  "en",     # ISO code; applied on restart (core/i18n.py)
    # When True, file open/save/folder pickers use the OS-native dialog instead
    # of ChromIQ's themed one. Native is much faster to populate on Windows, but
    # it's the OS's own dialog: it can't carry ChromIQ's custom sidebar shortcuts
    # or the built-in image-preview pane (Qt/OS limitation — see ui/widgets.py).
    "use_native_file_dialogs":   False,
    "show_welcome_dialog":       True,
    "window_maximized":          False,
    "window_fullscreen":         False,
    # Session restore — only the target name is stored; every artefact path is
    # derived from the project's current run on restore (see main_window).
    "session_target_name":       "",
    # Diagnostics — off by default; flip to True to log per-strip highlighter
    # math (id, global_idx, page, local_idx) to chromiq.log for investigating
    # detection drift.
    "debug_highlighter":         False,
    # Margin inspector (Create Chart) — measure the realised page margins of the
    # generated preview, compare to per-(instrument, paper+orientation) minimum
    # thresholds, and flag violations for jig/rig users.
    "margin_inspector_show":     True,    # show the "Measured from Preview" frame
    "layout_info_show":          True,    # show the "Chart layout information" panel
    "margin_violation_notify":   True,    # warn when a measured margin < threshold
    "margin_guides_show":        False,   # dotted threshold guide lines on preview
    "margin_measured_guides_show": False,  # long dotted lines at the measured margins
    "margin_thresholds":         "",      # JSON blob; "" → default_margin_thresholds()
    # Scanner/camera profiling: misalignment-check thresholds (Knut #108).
    # Editable in Settings → Scanner; the defaults carry a buffer for real
    # scans (noisier than the built-in demo images).
    #   (the ΔE-vs-aims share check was retired in beta.130 — real prints
    #   can't reach the chart's ideal aims, so it flagged aligned scans)
    "scanner_selfcheck_peak":    30.0,    # colprof self-check peak err → warning
    "scanner_selfcheck_avg":     12.0,    # …AND avg err must exceed this too
    # Check-alignment probe verdict: the user's position competes with the
    # 8-direction probe star on Knut's normalised scale (best probe = 1,
    # worst = 0). Calibrated on his real Wolf Faust scan so a 25 % grid
    # offset flags and ≤15 % passes at 50 % sample area (#108).
    "scanner_check_agreement":   0.85,
    # Flank override (Knut's derivative design): patch borders are LINES of
    # high spatial gradient (centred, two scales — symmetric in all 8
    # directions); a box is ON an edge when 3+ CONNECTED sub-cells of its
    # 9x9 grid carry a peak above the grain floor (a line crosses adjacent
    # cells, dust scatters) AND the box is clean at some nearby position.
    # 7+ such boxes flag the page over the ladder floor. Calibrated on his
    # real scans: aligned <=6 boxes (LaserSoft's printed bars ARE edges
    # near some box rims), just-crossing offsets 20-160.
    "scanner_flank_limit":       0.30,
    # Settings → Paths (Knut #108): where "Install profile" copies the .icc.
    # Empty = the platform's per-user colour-profile folder.
    "profile_install_dir":       "",
    # Strip-indicator styling (Knut #93): the per-chart detail controls moved to
    # Settings → Chart Layout. These are the app-wide DEFAULTS used for new charts;
    # presets still carry (and restore) their own styling. Keys mirror the
    # LayoutRecipe.indicator_* / underline_* / strip_label_offset fields.
    "strip_indicator_font":          "JetBrains Mono",
    "strip_indicator_size_mm":       0.0,   # 0 = auto (instrument text height)
    "strip_indicator_bold":          False,
    "strip_indicator_italic":        False,
    "strip_indicator_rotation":      0,     # 0 | 90 | 180 | 270
    "strip_indicator_align":         "left",
    "strip_label_offset_mm":         0.0,
    "strip_underline_mode":          "off",  # "off" | "colored" | "black"
    "strip_underline_thickness_mm":  0.5,
    "strip_underline_gap_mm":        0.5,
}

# Map LayoutRecipe styling field → its settings key, so the panel and the
# recipe-overlay helper agree (Knut #93). show_strip_indicators stays per-chart.
INDICATOR_STYLE_KEYS = {
    "indicator_font":          "strip_indicator_font",
    "indicator_size_mm":       "strip_indicator_size_mm",
    "indicator_bold":          "strip_indicator_bold",
    "indicator_italic":        "strip_indicator_italic",
    "indicator_rotation":      "strip_indicator_rotation",
    "indicator_align":         "strip_indicator_align",
    "strip_label_offset_mm":   "strip_label_offset_mm",
    "underline_mode":          "strip_underline_mode",
    "underline_thickness_mm":  "strip_underline_thickness_mm",
    "underline_gap_mm":        "strip_underline_gap_mm",
}


# ---------------------------------------------------------------------------
# Margin-threshold seed defaults
# ---------------------------------------------------------------------------
# Per-(instrument, paper+orientation) minimum margins (mm) the inspector warns
# below. Keyed "<instrument>|<paper> <Orientation>". These are *editable seed
# values* (a starting point users adjust to their own rig), NOT physical minima.
# The i1Pro values come from the X-Rite/enlarged-ruler analysis (≈11 mm white
# run-up on the narrow side, the label side ending up larger). ColorMunki seeds
# are derived empirically from the shipped, practically-tested presets
# (scripts/derive_margin_seeds.py).
#
# The white run-up the i1Pro/ColorMunki needs is along the **scan direction**
# (the strip length). printtarg lays strips down the page, so for a *portrait*
# sheet the scan-direction edges are Top and Bottom; for *landscape*, Left and
# Right. Cross-scan side margins (the other pair) aren't the binding constraint,
# so they're left at 0 (unchecked) — which also stops shipped presets (e.g. the
# i1Pro A4 chart's 8 mm cross-scan margin) from false-alarming. ColorMunki values
# are derived empirically from the shipped, practically-tested presets
# (scripts/derive_margin_seeds.py: Top ≈ 24 mm, Bottom ≈ 11 mm) and rounded just
# below the smallest known-good margin so those presets read OK out of the box.
_I1_DESC = "i1Pro ruler / jig"
_CM_DESC = "ColorMunki ruler / jig"
# Knut #82: thresholds are 10 mm sides/bottom + 24 mm Top (label edge) for the
# i1Pro, and 6 mm sides/bottom + 24 mm Top for the ColorMunki. ColorMunki uses
# the same values for *every* paper size, so its seeds cover all papers × both
# orientations; the i1Pro table lists the orientations its presets actually use.
# (Top is still tentative — editable per combo.)
_MARGIN_PAPERS_ALL = ("A4", "Letter", "A3", "A3+", "A2", "Tabloid", "Legal")


def _seed_rows(instr, desc, side, top, combos):
    return {
        f"{instr}|{paper} {orient}":
            {"L": side, "R": side, "T": top, "B": side, "desc": desc}
        for paper, orient in combos
    }


# i1Pro confirmed values (#82): the primary reading orientation of each common
# paper needs the 26 mm left clip border, 38 mm label-edge top, 9 mm elsewhere;
# every other i1Pro paper/orientation gets a plain 9 mm all round.
_I1_PRIMARY = {"L": 26, "R": 9, "T": 38, "B": 9, "desc": _I1_DESC}
# i1Pro 3+ (#82): the larger body needs a touch more on the clip + label edges
# (28 / 40 instead of 26 / 38); provisional until confirmed.
_I1P3_DESC = "i1Pro 3+ ruler / jig"
_I1P3_PRIMARY = {"L": 28, "R": 9, "T": 40, "B": 9, "desc": _I1P3_DESC}
_PRIMARY_COMBOS = (
    "A4 Portrait", "Letter Portrait", "A3 Landscape", "Tabloid Landscape")
_ALL_COMBOS = [(p, o) for p in _MARGIN_PAPERS_ALL
               for o in ("Portrait", "Landscape")]
_MARGIN_SEED: dict[str, dict[str, Any]] = {
    **_seed_rows("i1Pro", _I1_DESC, 9, 9, _ALL_COMBOS),
    **{f"i1Pro|{c}": dict(_I1_PRIMARY) for c in _PRIMARY_COMBOS},
    **_seed_rows("i1Pro 3+", _I1P3_DESC, 9, 9, _ALL_COMBOS),
    **{f"i1Pro 3+|{c}": dict(_I1P3_PRIMARY) for c in _PRIMARY_COMBOS},
    **_seed_rows("ColorMunki", _CM_DESC, 6, 24, _ALL_COMBOS),
}


def default_margin_thresholds() -> dict[str, dict[str, Any]]:
    """A fresh copy of the seed threshold table (see :data:`_MARGIN_SEED`)."""
    import copy

    return copy.deepcopy(_MARGIN_SEED)


def parse_margin_thresholds(raw: str) -> dict[str, dict[str, Any]]:
    """Decode the stored margin-threshold JSON blob (``""`` → seed defaults)."""
    import json

    if not raw:
        return default_margin_thresholds()
    try:
        doc = json.loads(raw)
        if isinstance(doc, dict):
            return doc
    except (ValueError, TypeError):
        log.warning("Corrupt margin_thresholds blob — using seed defaults")
    return default_margin_thresholds()


def serialize_margin_thresholds(table: dict[str, dict[str, Any]]) -> str:
    import json

    return json.dumps(table, ensure_ascii=False)


def margin_combo_key(instrument: str, paper: str, orientation: str) -> str:
    """Canonical "<instrument>|<paper> <Orientation>" threshold key."""
    paper = (paper or "").strip()
    orientation = (orientation or "").strip().capitalize()
    suffix = f" {orientation}" if orientation else ""
    return f"{instrument}|{paper}{suffix}"


# Engine instrument flag → margin-threshold instrument label (matches the seed
# keys + settings_dialog._MARGIN_INSTRUMENTS).
THRESHOLD_INSTR_LABEL = {
    "i1": "i1Pro", "p3": "i1Pro 3+", "CM": "ColorMunki",
    "SS": "SpectroScan", "isis": "i1iSis",
}

# Canonical sheet name keyed by sorted (short, long) mm — so any paper code
# (named, "WxH", rotated) maps to one threshold-combo paper name; orientation is
# carried separately. Mirrors ui.tabs.tab_chart._CANON_PAPER_BY_DIMS.
_CANON_PAPER_BY_DIMS = {
    (210.0, 297.0): "A4",
    (215.9, 279.4): "Letter",
    (215.9, 355.6): "Legal",
    (297.0, 420.0): "A3",
    (329.0, 483.0): "A3+",
    (420.0, 594.0): "A2",
    (279.4, 431.8): "Tabloid",
}


def canonical_paper_name(w_mm: float, h_mm: float) -> "str | None":
    """Best-effort canonical sheet name from page dimensions (mm), or None.

    Tolerant to ~2.5 mm so a measured page still matches a named size."""
    lo, hi = sorted((w_mm, h_mm))
    for (clo, chi), name in _CANON_PAPER_BY_DIMS.items():
        if abs(lo - clo) <= 2.5 and abs(hi - chi) <= 2.5:
            return name
    return None


def thresholds_for_combo(
    table: "dict[str, dict[str, Any]]", instrument_flag: str,
    w_mm: float, h_mm: float,
) -> "dict[str, Any] | None":
    """The margin-threshold entry for an engine instrument flag + page size, or
    None when the combo has no thresholds. Used to enforce the user's minimums
    in the layout engine (#93)."""
    label = THRESHOLD_INSTR_LABEL.get(instrument_flag)
    name = canonical_paper_name(w_mm, h_mm)
    if not label or not name:
        return None
    orientation = "Landscape" if w_mm > h_mm else "Portrait"
    return (table or {}).get(margin_combo_key(label, name, orientation))


class AppSettings:
    def __init__(self) -> None:
        self._qs = QSettings("ChromIQ", "ChromIQ")
        log.debug("Settings loaded from %s", self._qs.fileName())

    def get(self, key: str, default: Any = None) -> Any:
        # On Windows the OS print dialog is the only path that works (no CUPS,
        # no driver-side colour-management toggle we can reach from PostScript).
        # Force the setting True regardless of stored value so a stale False
        # carried over from an older install can't strand the user on the
        # non-functional bypass UI.
        if key == "use_native_print_dialog" and is_windows():
            return True
        fallback = DEFAULTS.get(key, default)
        val = self._qs.value(key, fallback)
        # QSettings can return strings for booleans — coerce
        if isinstance(fallback, bool) and isinstance(val, str):
            val = val.lower() in ("true", "1", "yes")
        elif isinstance(fallback, int) and isinstance(val, str):
            try:
                val = int(val)
            except ValueError:
                val = fallback
        elif isinstance(fallback, float) and isinstance(val, str):
            try:
                val = float(val)
            except ValueError:
                val = fallback
        return val

    def set(self, key: str, value: Any) -> None:
        log.debug("settings.set %s = %r", key, value)
        self._qs.setValue(key, value)

    def reset_to_defaults(self) -> None:
        presets = self._qs.value("manual_presets", "")
        self._qs.clear()
        if presets:
            self._qs.setValue("manual_presets", presets)
        log.info("Settings reset to factory defaults")

    def save_tab_defaults(self, prefix: str, values: dict[str, Any]) -> None:
        """Save a dict of key→value under a given prefix."""
        for k, v in values.items():
            self.set(f"{prefix}_{k}", v)

    # ------------------------------------------------------------------
    # Margin thresholds (JSON blob; see default_margin_thresholds)
    # ------------------------------------------------------------------
    def get_margin_thresholds(self) -> dict[str, dict[str, Any]]:
        """The per-combo margin-threshold table, falling back to the seeds.

        Stored as a JSON string under ``margin_thresholds`` so the whole
        editable matrix round-trips through QSettings as one value.
        """
        return parse_margin_thresholds(self.get("margin_thresholds", ""))

    def set_margin_thresholds(self, table: dict[str, dict[str, Any]]) -> None:
        self.set("margin_thresholds", serialize_margin_thresholds(table))

    # ------------------------------------------------------------------
    # Strip-indicator styling defaults (Knut #93)
    # ------------------------------------------------------------------
    def indicator_style(self) -> dict[str, Any]:
        """The app-wide strip-indicator styling as ``{recipe_field: value}``
        (typed to each DEFAULTS entry), for seeding a fresh chart's recipe."""
        return {field: self.get(key) for field, key in INDICATOR_STYLE_KEYS.items()}

    def apply_indicator_style(self, recipe):
        """Return *recipe* with its strip-indicator styling fields overlaid from
        the app-wide defaults (used for new charts; presets keep their own)."""
        from dataclasses import replace
        return replace(recipe, **self.indicator_style())
